---
title: "PDF de projeto de lei para data.frame"
output: github_document
date: "2023-05-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sobre o texto do pdf

PDF de um projeto de lei.

Hierarquia:

> livro > título > Capítulo > seção > artigo > parágrafo > inciso > alínea

#### Exemplo de texto:

```{r, warning=FALSE, message=FALSE}
library(tidyverse, warn.conflicts = FALSE)
`%|NA|%` <- function(lhr, rhs) ifelse(is.na(lhr), rhs, lhr)
paginas <- pdftools::pdf_text("DOC-Avulso inicial da matéria - SF212063437642-20210916.pdf")
cat(paginas[[5]])
```

## Tratamento inicial

Primeiro juntar todas as páginas em uma única string para as quebras de página não atrapalhar.

```{r cars}
# limpa coisas inúteis, principalmente do rodapé
limpeza_basica <- function(texto) {
  texto %>%
    # remove coisa do tipo "Documento : 90944 - 11"
    str_remove_all("Documento : [0-9]{1,6} - [0-9]{1,6}") %>%
    # remove coisa do tipo "*$238650$220531$*"
    str_remove_all("\\*\\$[0-9$]+\\$\\*") %>%
    # remove coisa do tipo "Página 4 de 393"
    str_remove_all("Página [0-9]{1,3} de 393") %>%
    # remove coisa do tipo ""Avulso do PLP 112/2021."
    str_remove_all("Avulso do PLP 112/2021\\.")
}

documento <- paginas %>%
  str_c(collapse = "") %>%
  limpeza_basica()
```

## Livros

```{r}
livros <- documento %>% 
  str_split_1("(?=LIVRO )") %>%
  enframe(name = "livro", value = "conteudo") %>%
  mutate(
    livro = str_extract(conteudo, "LIVRO [IVXDLCM]+") %|NA|% "_VAZIO_",
    conteudo = str_remove(conteudo, fixed(livro))
  ) 
livros %>% count(livro)
```

## Títulos

```{r}
titulos <- livros %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?=TÍTULO )") %>%
        enframe(name = "titulo", value = "conteudo") %>%
        mutate(
          titulo = str_extract(conteudo, "TÍTULO ([IVXDLCM]+|ÚNICO)") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(titulo))
        ) 
    })
  ) %>% 
  unnest(conteudo)
titulos %>% count(titulo)
```

## Capítulos

```{r}
capitulos <- titulos %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?=CAPÍTULO )") %>%
        enframe(name = "capitulo", value = "conteudo") %>%
        mutate(
          capitulo = str_extract(conteudo, "CAPÍTULO ([IVXDLCM]+|ÚNICO)") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(capitulo))
        ) 
    })
  ) %>% 
  unnest(conteudo)
capitulos %>% count(capitulo)
```

## Seções

```{r}
secoes <- titulos %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?=Seção )") %>%
        enframe(name = "secao", value = "conteudo") %>%
        mutate(
          secao = str_extract(conteudo, "Seção ([IVXDLCM]+|Única)") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(secao))
        ) 
    })
  ) %>% 
  unnest(conteudo)
secoes %>% count(secao)
```

## Artigos

```{r}
artigos <- secoes %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?=Art\\. )") %>%
        enframe(name = "artigo", value = "conteudo") %>%
        mutate(
          artigo = str_extract(conteudo, "Art\\. +[0-9]+ *[º°.]") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(artigo))
        )
    })
  ) %>% 
  unnest(conteudo)
artigos %>% count(artigo)
```


## Parágrafos

```{r}
paragrafos <- artigos %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?=   (§|Parágrafo) )") %>%
        enframe(name = "paragrafo", value = "conteudo") %>%
        mutate(
          paragrafo = str_extract(conteudo, "   (§ +[0-9]+ *[º°.]|Parágrafo único\\.)") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(paragrafo)),
          paragrafo = str_replace(paragrafo, " *[°º]", "º") %>% str_squish(),
        )
    })
  ) %>% 
  unnest(conteudo)
paragrafos %>% count(paragrafo)
```

## Incisos

```{r}
incisos <- paragrafos %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?= {5}[IVXDLCM]+ )") %>%
        enframe(name = "inciso", value = "conteudo") %>%
        mutate(
          inciso = str_extract(conteudo, "^ {5}[IVXDLCM]+[– -]+ ") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(inciso)),
          inciso = str_remove_all(inciso, "[– -]")
        )
    })
  ) %>% 
  unnest(conteudo)
incisos %>% count(inciso)
```


## Alíneas

```{r}
alineas <- incisos %>%
  mutate( 
    conteudo = map(conteudo, function(conteudo) {
      conteudo %>% 
        str_split_1("(?= {5}[a-z]{1,2}\\) )") %>%
        enframe(name = "alinea", value = "conteudo") %>%
        mutate(
          alinea = str_extract(conteudo, "^ {5}[a-z]{1,2}\\) ") %|NA|% "_VAZIO_",
          conteudo = str_remove(conteudo, fixed(alinea)),
          alinea = str_remove_all(alinea, "[ )]"),
        )
    })
  ) %>% 
  unnest(conteudo)
alineas %>% count(alinea)
```

## Tabela final

```{r}
tabela_final <- alineas %>%
  mutate(
    across(everything(), str_squish),
    across(everything(), ~ str_replace(.x, "_VAZIO_", ""))
  )

tabela_final %>%
  mutate(conteudo = str_trunc(conteudo, 25)) %>%
  head(20) %>%
  knitr::kable()
```

```{r}
# writexl::write_xlsx(tabela_final, "DOC-Avulso inicial da matéria - SF212063437642-20210916.xlsx")
```

